apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    requests.storage: "50Gi"
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
